stages:
  - build
  - release

.dind:
  image: docker:stable
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login ${CI_REGISTRY} -u gitlab-ci-token -p ${CI_JOB_TOKEN}

build latest:
  extends: .dind
  stage: build
  script:
    # - docker buildx create --driver=docker-container --use
    - docker buildx build --push --progress=plain
        --build-arg BUILD_VERSION=latest
        --platform linux/arm64,linux/amd64
        --tag ${CI_REGISTRY_IMAGE}:latest
        --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}:cache
        --cache-to type=registry,ref=${CI_REGISTRY_IMAGE}:cache,mode=max
        .
  only:
    - master
  except:
    - tags

build stable:
  extends: .dind
  stage: release
  script:
    - docker buildx create --driver=docker-container --use
    - docker buildx build --push --progress=plain
        --build-arg BUILD_VERSION=${CI_COMMIT_TAG}
        --platform linux/arm64,linux/amd64
        --tag=${CI_REGISTRY_IMAGE}:latest
        --tag=${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
        --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}:cache
        --cache-to type=registry,ref=${CI_REGISTRY_IMAGE}:cache,mode=max
        .
  only:
    - tags
