version: "3.8"
services:
  server:
    build:
      context: .
      args:
        TARGETOS: ${DC_TARGETOS}
        TARGETARCH: ${DC_TARGETARCH}
    entrypoint: ["indexer"]
    command: ["-reset", "-hidebar"]
