version: "3.8"
services:
  fb2lib:
    image: ${DC_APP_IMG:-fb2lib:debug}
    ports:
      - ${DC_APP_PORT:-80}:8080
    volumes:
      - ./var/libs/default:/var/libs/default:ro
      - ./var/index:/var/index:rw
      - ./var/db:/var/db:rw
