version: "3.8"
services:
  fb2lib:
    build:
      context: .
      args:
        TARGETOS: ${DC_TARGETOS:-linux}
        TARGETARCH: ${DC_TARGETARCH:-amd64}
    volumes:
      - ./configs/app.override.yml:/configs/app.override.yml:ro
    entrypoint: ["indexer"]
    command: ["-hidebar"]