version: "3.8"
services:
  server:
    image: ${DC_APP_IMG}
    env_file:
      - ./.env
    ports:
      - ${DC_SERVER_PORT}:${BS_SERVER_PORT}
    volumes:
      - ./var:/app/var:rw
      - ./web/library:/app/web/library:rw
    # entrypoint: ["bin/importer"]
