server:
  port: 8080
  debug: false
logs:
  debug: false
  pretty: false
  duration_unit: 1s
  dir: var/logs
bleve:
  index_dir: var/index/books
  highlight: true
library:
  dir: var/library
  converter_dir: var/cache/converter
renderer:
  tpl_dir: web/themes/massively
  globals:
    gtitle: fb2library
pprof:
  dir: var/pprof