server:
  port: 8080
  debug: false
logs:
  debug: false
  pretty: false
  color: false
  caller: false
  duration_unit: 1s
  dir: var/logs
bleve:
  highlight: true
  path: var/index
boltdb:
  path: var/storage/db.bolt
converter:
  dir: var/converter
renderer:
  tpl_dir: web/themes/editorial
  sidebar:
    genres_size: 10
  globals:
    page_title: FB2 Библиотека
    page_h1: FB2 Библиотека
    books_sizes: 20,40,100
    genres_size: 50
    section_name: home
pprof:
  dir: var/pprof
libraries:
  default:
    # disabled: true
    # order: 1
    dir: var/libs/default
    encoder: parser # or marshaler
    types: ["fb2", "zip"]
