debug: false
server:
  port: 8080
logs:
  debug: false
  pretty: false
  duration_unit: 1s
web:
  library_dir: web/library
  static_dir: web/static
  markup_dir: web/markup
bleve:
  books_dir: var/books_index
  highlight: true
