server:
  port: 8080
  debug: false
logs:
  debug: false
  pretty: false
  duration_unit: 1s
  dir: var/logs
bleve:
  highlight: true
  path: var/index
boltdb:
  path: var/storage/db.bolt
converter:
  dir: var/converter
renderer:
  tpl_dir: web/themes/editorial
  globals:
    gtitle: fb2library
pprof:
  dir: var/pprof
libraries:
  default:
    disabled: false
    dir: var/libs/default
    # encoder: marshaler # or parser
    types: [] # fb2,zip
