debug: false
server:
  port: 8080
logs:
  debug: false
  pretty: false
  duration_unit: 1s
markup:
  theme_dir: web/themes/massively
bleve:
  books_dir: var/books_index
  highlight: true
extractor:
  type: html # @TODO: switch to "local"
  dir: var/library
  uri_prefix: /library
