server:
  port: 8080
  debug: false
logs:
  debug: false
  pretty: false
  duration_unit: 1s
  dir: var/logs
markup:
  theme_dir: web/themes/massively
bleve:
  index_dir: var/index
  highlight: true
library:
  dir: var/library
  converter_dir: var/converter