server:
  port: 8080
  debug: false
logs:
  debug: false
  pretty: false
  color: false
  caller: false
  duration_unit: 1s
  dir: var/logs
adapters:
  bleve:
    dir: var/index
  badger:
    dir: var/db
converter:
  dir: var/converter
renderer:
  dir: web/themes/editorial
  sidebar:
    genres_size: 10
  globals:
    page_title: FB2 Библиотека
    page_h1: FB2 Библиотека
    books_sizes: 20,40,100
    genres_size: 50
    section_name: home
    alphabet_en: ABCDEFGHIJKLMNOPQRSTUWVXYZ
    alphabet_ru: АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЭЮЯ
pprof:
  dir: var/pprof
libraries:
  default:
    # disabled: true
    # order: 1
    dir: var/libs/default
    encoder: parser # or marshaler
    types: ["fb2", "zip"]
indexer:
  threads_cnt: 1
  read_buff: 0
  read_threads: 0
  parse_buff: 0
  parse_threads: 0
  batch_size: 200
