server:
  port: 8080
  debug: false
logs:
  debug: false
  pretty: false
  color: false
  caller: false
  duration_unit: 1s
  dir: var/logs
adapters:
  bleve:
    dir: var/index
  badger:
    dir: var/db
converter:
  dir: var/converter
pprof:
  dir: var/pprof
libraries:
  default:
    # disabled: true
    # order: 1
    dir: var/libs/default
    encoder: parser # or marshaler
    types: ["fb2", "zip"]
indexer:
  threads_cnt: 1
  read_buff: 0
  read_threads: 0
  parse_buff: 0
  parse_threads: 0
  batch_size: 200
renderer:
  dir: web/themes/adminlte
  sidebar:
    genres_size: 10
  globals:
    logo_text: FB2Lib
    page_title: Библиотека
    page_h1: Библиотека
    books_sizes: 21,45,150
    genres_size: 50
    authors_size: 50
    series_size: 50
    section_name: home
    alphabet_en: ABCDEFGHIJKLMNOPQRSTUWVXYZ
    alphabet_ru: АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЭЮЯ
    app_version: v0.0.0
  rules:
    only:
      langs: []
      genres: []
      authors: []
      titles: []
    except:
      langs: []
      genres: []
      authors: []
      titles: []