name: Latest
on: 
  push: 
    branches:
     - '*'
jobs:

  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 make build BUILD_VERSION=latest
          GOOS=linux GOARCH=arm64 make build BUILD_VERSION=latest
      - name: Read gitflow
        id: gitflow
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/egnd/fb2lib:${{ steps.gitflow.outputs.sha_short }}
          file: .ci/proxy.Dockerfile
