name: Latest
on:
  create:
    tags:
      - v*
jobs:
  push-latest:
    runs-on: ubuntu-latest
    needs: [build-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Read gitflow
        id: gitflow
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=tag_name::${GITHUB_REF##*/}"
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DHLGN }}
          password: ${{ secrets.DHPWD }}
      - uses: docker/build-push-action@v2
        with:
          context: .ci
          platforms: linux/amd64,linux/arm64
          push: true
          tags: egnd/fb2lib:${{ steps.gitflow.outputs.tag_name }}
          file: .ci/proxy.Dockerfile
          build-args: SRC_IMG=ghcr.io/egnd/fb2lib:${{ steps.gitflow.outputs.sha_short }}
